---
app_dir: /opt/sharetrip
app_image: ghcr.io/hisamist/sharetrip:latest
app_port: 8000
postgres_user: sharetrip

postgres_password: "mypassword123"
postgres_db: sharetrip
jwt_secret_key: "mysecretkey_minimum_32_characters_long"

app_env: production
